'use client';
import { useContext } from "react";
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/d65Xp0xCg3S
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import AuthContext from "@/hooks/auth-context";

export function Header() {

  const { logout, isLogged } = useContext(AuthContext);

  if (!isLogged) {
    return null;
  }

  return (
    <header className="flex items-center justify-between bg-[#604CC3] px-4 py-3 shadow-sm sm:px-6 text-primary-foreground">
      <div className="flex items-center gap-4">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6 fill-primary-foreground" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="hidden gap-4 sm:flex">
          <Link href="/products" className="font-medium text-primary-foreground hover:text-foreground" prefetch={false}>
            Products
          </Link>
          <Link href="/" className="font-medium text-primary-foreground hover:text-foreground" prefetch={false}>
            Dashboard
          </Link>
          <Link href="/User/listView" className="font-medium text-primary-foreground hover:text-foreground" prefetch={false}>
            Usuarios
          </Link>
        </nav>
      </div>
      <div className="flex items-center gap-4">
        <Badge variant="outline" className="border-[#604CC3] bg-background text-[#604CC3]">
          <CircleIcon className="h-3 w-3 -translate-x-1 animate-pulse fill-[#604CC3] text-[#604CC3]" />
          {isLogged ? "Online" : "Offline"}
        </Badge>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon" className="overflow-hidden rounded-full">
              <div
                className="flex items-center justify-center bg-gray-300 text-white rounded-full"
                style={{ width: 36, height: 36, fontSize: 18 }}
              >
                A
              </div>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>My Account</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Settings</DropdownMenuItem>
            <DropdownMenuItem>Support</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={logout}>Logout</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </header>
  )
}

function CircleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}


function MountainIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
