'use client';
import AuthContext from '@/hooks/auth-context';
import { log } from 'console';
import { useRouter } from 'next/navigation'
import { useContext } from 'react';
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mmSiMuPW7e2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function LoginForm() {

  const router = useRouter();
  const { login } = useContext(AuthContext);

  const handleSubmit = (e: any) => {
    e.preventDefault()
    const username = e.target.username.value
    const password = e.target.password.value

    fetch('http://localhost:3001/auth/login', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ username, password })
    })
      .then((res) => {
        if (res.status === 401) {
          throw new Error('Unauthorized');
        }
        return res.json();
      })
      .then((data) => {
        // Save token and userId to localStorage
        localStorage.setItem('token', data.token);
        login();
        router.push('/');
        console.log(localStorage.getItem('token'));
      })
      .catch((error) => {
        console.error(error);
        // Handle unauthorized error here
      });
  }

  return (
    <div className="flex items-center justify-center h-screen bg-gradient-to-br from-[#503dab] to-[#604CC3]">
      <div className="w-full max-w-md p-8 bg-white rounded-lg shadow-lg animate-fade-in">
        <div className="mb-8 text-center">
          <h2 className="text-3xl font-bold">Bienvenido</h2>
        </div>
        <form className="space-y-6" onSubmit={handleSubmit}>
          <div>
            <label htmlFor="username" className="block mb-2 text-sm font-medium text-gray-700">
              Nombre de usuario
            </label>
            <input
              id="username"
              type="text"
              placeholder="Ingresar usuario"
              className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#604CC3] focus:border-transparent animate-fade-in"
            />
          </div>
          <div>
            <label htmlFor="password" className="block mb-2 text-sm font-medium text-gray-700">
              Contraseña
            </label>
            <input
              id="password"
              type="password"
              placeholder="••••••••"
              className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#FF7F3E] focus:border-transparent animate-fade-in"
            />
          </div>
          <button
            type="submit"
            className="w-full px-4 py-3 font-medium text-white bg-[#604CC3] rounded-md hover:bg-[#604CC3] focus:outline-none focus:ring-2 focus:ring-[#604CC3] focus:ring-offset-2 animate-fade-in"
          >
            Iniciar sesión
          </button>
        </form>
      </div>
    </div>
  )
}
